// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TourProductsColumns holds the columns for the "tour_products" table.
	TourProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "user_products", Type: field.TypeString, Nullable: true},
	}
	// TourProductsTable holds the schema information for the "tour_products" table.
	TourProductsTable = &schema.Table{
		Name:       "tour_products",
		Columns:    TourProductsColumns,
		PrimaryKey: []*schema.Column{TourProductsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tour_products_use_rs_products",
				Columns:    []*schema.Column{TourProductsColumns[2]},
				RefColumns: []*schema.Column{UseRsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UseRsColumns holds the columns for the "use_rs" table.
	UseRsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "is_activated", Type: field.TypeBool, Default: true},
	}
	// UseRsTable holds the schema information for the "use_rs" table.
	UseRsTable = &schema.Table{
		Name:       "use_rs",
		Columns:    UseRsColumns,
		PrimaryKey: []*schema.Column{UseRsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TourProductsTable,
		UseRsTable,
	}
)

func init() {
	TourProductsTable.ForeignKeys[0].RefTable = UseRsTable
}
