// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UseRsColumns holds the columns for the "use_rs" table.
	UseRsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(10)"}},
		{Name: "email", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(20)"}},
		{Name: "create_at", Type: field.TypeTime},
		{Name: "update_at", Type: field.TypeTime},
	}
	// UseRsTable holds the schema information for the "use_rs" table.
	UseRsTable = &schema.Table{
		Name:       "use_rs",
		Columns:    UseRsColumns,
		PrimaryKey: []*schema.Column{UseRsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UseRsTable,
	}
)

func init() {
}
