// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blohny/ent/predicate"
	"github.com/blohny/ent/tourproduct"
)

// TourProductQuery is the builder for querying TourProduct entities.
type TourProductQuery struct {
	config
	ctx        *QueryContext
	order      []tourproduct.OrderOption
	inters     []Interceptor
	predicates []predicate.TourProduct
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TourProductQuery builder.
func (tpq *TourProductQuery) Where(ps ...predicate.TourProduct) *TourProductQuery {
	tpq.predicates = append(tpq.predicates, ps...)
	return tpq
}

// Limit the number of records to be returned by this query.
func (tpq *TourProductQuery) Limit(limit int) *TourProductQuery {
	tpq.ctx.Limit = &limit
	return tpq
}

// Offset to start from.
func (tpq *TourProductQuery) Offset(offset int) *TourProductQuery {
	tpq.ctx.Offset = &offset
	return tpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tpq *TourProductQuery) Unique(unique bool) *TourProductQuery {
	tpq.ctx.Unique = &unique
	return tpq
}

// Order specifies how the records should be ordered.
func (tpq *TourProductQuery) Order(o ...tourproduct.OrderOption) *TourProductQuery {
	tpq.order = append(tpq.order, o...)
	return tpq
}

// First returns the first TourProduct entity from the query.
// Returns a *NotFoundError when no TourProduct was found.
func (tpq *TourProductQuery) First(ctx context.Context) (*TourProduct, error) {
	nodes, err := tpq.Limit(1).All(setContextOp(ctx, tpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tourproduct.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tpq *TourProductQuery) FirstX(ctx context.Context) *TourProduct {
	node, err := tpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TourProduct ID from the query.
// Returns a *NotFoundError when no TourProduct ID was found.
func (tpq *TourProductQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tpq.Limit(1).IDs(setContextOp(ctx, tpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tourproduct.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tpq *TourProductQuery) FirstIDX(ctx context.Context) int {
	id, err := tpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TourProduct entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TourProduct entity is found.
// Returns a *NotFoundError when no TourProduct entities are found.
func (tpq *TourProductQuery) Only(ctx context.Context) (*TourProduct, error) {
	nodes, err := tpq.Limit(2).All(setContextOp(ctx, tpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tourproduct.Label}
	default:
		return nil, &NotSingularError{tourproduct.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tpq *TourProductQuery) OnlyX(ctx context.Context) *TourProduct {
	node, err := tpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TourProduct ID in the query.
// Returns a *NotSingularError when more than one TourProduct ID is found.
// Returns a *NotFoundError when no entities are found.
func (tpq *TourProductQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tpq.Limit(2).IDs(setContextOp(ctx, tpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tourproduct.Label}
	default:
		err = &NotSingularError{tourproduct.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tpq *TourProductQuery) OnlyIDX(ctx context.Context) int {
	id, err := tpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TourProducts.
func (tpq *TourProductQuery) All(ctx context.Context) ([]*TourProduct, error) {
	ctx = setContextOp(ctx, tpq.ctx, "All")
	if err := tpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TourProduct, *TourProductQuery]()
	return withInterceptors[[]*TourProduct](ctx, tpq, qr, tpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tpq *TourProductQuery) AllX(ctx context.Context) []*TourProduct {
	nodes, err := tpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TourProduct IDs.
func (tpq *TourProductQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tpq.ctx.Unique == nil && tpq.path != nil {
		tpq.Unique(true)
	}
	ctx = setContextOp(ctx, tpq.ctx, "IDs")
	if err = tpq.Select(tourproduct.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tpq *TourProductQuery) IDsX(ctx context.Context) []int {
	ids, err := tpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tpq *TourProductQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tpq.ctx, "Count")
	if err := tpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tpq, querierCount[*TourProductQuery](), tpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tpq *TourProductQuery) CountX(ctx context.Context) int {
	count, err := tpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tpq *TourProductQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tpq.ctx, "Exist")
	switch _, err := tpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tpq *TourProductQuery) ExistX(ctx context.Context) bool {
	exist, err := tpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TourProductQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tpq *TourProductQuery) Clone() *TourProductQuery {
	if tpq == nil {
		return nil
	}
	return &TourProductQuery{
		config:     tpq.config,
		ctx:        tpq.ctx.Clone(),
		order:      append([]tourproduct.OrderOption{}, tpq.order...),
		inters:     append([]Interceptor{}, tpq.inters...),
		predicates: append([]predicate.TourProduct{}, tpq.predicates...),
		// clone intermediate query.
		sql:  tpq.sql.Clone(),
		path: tpq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TourProduct.Query().
//		GroupBy(tourproduct.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tpq *TourProductQuery) GroupBy(field string, fields ...string) *TourProductGroupBy {
	tpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TourProductGroupBy{build: tpq}
	grbuild.flds = &tpq.ctx.Fields
	grbuild.label = tourproduct.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.TourProduct.Query().
//		Select(tourproduct.FieldName).
//		Scan(ctx, &v)
func (tpq *TourProductQuery) Select(fields ...string) *TourProductSelect {
	tpq.ctx.Fields = append(tpq.ctx.Fields, fields...)
	sbuild := &TourProductSelect{TourProductQuery: tpq}
	sbuild.label = tourproduct.Label
	sbuild.flds, sbuild.scan = &tpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TourProductSelect configured with the given aggregations.
func (tpq *TourProductQuery) Aggregate(fns ...AggregateFunc) *TourProductSelect {
	return tpq.Select().Aggregate(fns...)
}

func (tpq *TourProductQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tpq); err != nil {
				return err
			}
		}
	}
	for _, f := range tpq.ctx.Fields {
		if !tourproduct.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tpq.path != nil {
		prev, err := tpq.path(ctx)
		if err != nil {
			return err
		}
		tpq.sql = prev
	}
	return nil
}

func (tpq *TourProductQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TourProduct, error) {
	var (
		nodes   = []*TourProduct{}
		withFKs = tpq.withFKs
		_spec   = tpq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, tourproduct.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TourProduct).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TourProduct{config: tpq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tpq *TourProductQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tpq.querySpec()
	_spec.Node.Columns = tpq.ctx.Fields
	if len(tpq.ctx.Fields) > 0 {
		_spec.Unique = tpq.ctx.Unique != nil && *tpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tpq.driver, _spec)
}

func (tpq *TourProductQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tourproduct.Table, tourproduct.Columns, sqlgraph.NewFieldSpec(tourproduct.FieldID, field.TypeInt))
	_spec.From = tpq.sql
	if unique := tpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tpq.path != nil {
		_spec.Unique = true
	}
	if fields := tpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tourproduct.FieldID)
		for i := range fields {
			if fields[i] != tourproduct.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tpq *TourProductQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tpq.driver.Dialect())
	t1 := builder.Table(tourproduct.Table)
	columns := tpq.ctx.Fields
	if len(columns) == 0 {
		columns = tourproduct.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tpq.sql != nil {
		selector = tpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tpq.ctx.Unique != nil && *tpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tpq.predicates {
		p(selector)
	}
	for _, p := range tpq.order {
		p(selector)
	}
	if offset := tpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TourProductGroupBy is the group-by builder for TourProduct entities.
type TourProductGroupBy struct {
	selector
	build *TourProductQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tpgb *TourProductGroupBy) Aggregate(fns ...AggregateFunc) *TourProductGroupBy {
	tpgb.fns = append(tpgb.fns, fns...)
	return tpgb
}

// Scan applies the selector query and scans the result into the given value.
func (tpgb *TourProductGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tpgb.build.ctx, "GroupBy")
	if err := tpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TourProductQuery, *TourProductGroupBy](ctx, tpgb.build, tpgb, tpgb.build.inters, v)
}

func (tpgb *TourProductGroupBy) sqlScan(ctx context.Context, root *TourProductQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tpgb.fns))
	for _, fn := range tpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tpgb.flds)+len(tpgb.fns))
		for _, f := range *tpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TourProductSelect is the builder for selecting fields of TourProduct entities.
type TourProductSelect struct {
	*TourProductQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tps *TourProductSelect) Aggregate(fns ...AggregateFunc) *TourProductSelect {
	tps.fns = append(tps.fns, fns...)
	return tps
}

// Scan applies the selector query and scans the result into the given value.
func (tps *TourProductSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tps.ctx, "Select")
	if err := tps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TourProductQuery, *TourProductSelect](ctx, tps.TourProductQuery, tps, tps.inters, v)
}

func (tps *TourProductSelect) sqlScan(ctx context.Context, root *TourProductQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tps.fns))
	for _, fn := range tps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
