// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blohny/ent/predicate"
	"github.com/blohny/ent/user"
)

// USERUpdate is the builder for updating USER entities.
type USERUpdate struct {
	config
	hooks    []Hook
	mutation *USERMutation
}

// Where appends a list predicates to the USERUpdate builder.
func (uu *USERUpdate) Where(ps ...predicate.USER) *USERUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetName sets the "name" field.
func (uu *USERUpdate) SetName(s string) *USERUpdate {
	uu.mutation.SetName(s)
	return uu
}

// SetEmail sets the "email" field.
func (uu *USERUpdate) SetEmail(s string) *USERUpdate {
	uu.mutation.SetEmail(s)
	return uu
}

// SetCreateAt sets the "create_at" field.
func (uu *USERUpdate) SetCreateAt(t time.Time) *USERUpdate {
	uu.mutation.SetCreateAt(t)
	return uu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (uu *USERUpdate) SetNillableCreateAt(t *time.Time) *USERUpdate {
	if t != nil {
		uu.SetCreateAt(*t)
	}
	return uu
}

// SetUpdateAt sets the "update_at" field.
func (uu *USERUpdate) SetUpdateAt(t time.Time) *USERUpdate {
	uu.mutation.SetUpdateAt(t)
	return uu
}

// Mutation returns the USERMutation object of the builder.
func (uu *USERUpdate) Mutation() *USERMutation {
	return uu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *USERUpdate) Save(ctx context.Context) (int, error) {
	uu.defaults()
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *USERUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *USERUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *USERUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uu *USERUpdate) defaults() {
	if _, ok := uu.mutation.UpdateAt(); !ok {
		v := user.UpdateDefaultUpdateAt()
		uu.mutation.SetUpdateAt(v)
	}
}

func (uu *USERUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := uu.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := uu.mutation.CreateAt(); ok {
		_spec.SetField(user.FieldCreateAt, field.TypeTime, value)
	}
	if value, ok := uu.mutation.UpdateAt(); ok {
		_spec.SetField(user.FieldUpdateAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// USERUpdateOne is the builder for updating a single USER entity.
type USERUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *USERMutation
}

// SetName sets the "name" field.
func (uuo *USERUpdateOne) SetName(s string) *USERUpdateOne {
	uuo.mutation.SetName(s)
	return uuo
}

// SetEmail sets the "email" field.
func (uuo *USERUpdateOne) SetEmail(s string) *USERUpdateOne {
	uuo.mutation.SetEmail(s)
	return uuo
}

// SetCreateAt sets the "create_at" field.
func (uuo *USERUpdateOne) SetCreateAt(t time.Time) *USERUpdateOne {
	uuo.mutation.SetCreateAt(t)
	return uuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (uuo *USERUpdateOne) SetNillableCreateAt(t *time.Time) *USERUpdateOne {
	if t != nil {
		uuo.SetCreateAt(*t)
	}
	return uuo
}

// SetUpdateAt sets the "update_at" field.
func (uuo *USERUpdateOne) SetUpdateAt(t time.Time) *USERUpdateOne {
	uuo.mutation.SetUpdateAt(t)
	return uuo
}

// Mutation returns the USERMutation object of the builder.
func (uuo *USERUpdateOne) Mutation() *USERMutation {
	return uuo.mutation
}

// Where appends a list predicates to the USERUpdate builder.
func (uuo *USERUpdateOne) Where(ps ...predicate.USER) *USERUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *USERUpdateOne) Select(field string, fields ...string) *USERUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated USER entity.
func (uuo *USERUpdateOne) Save(ctx context.Context) (*USER, error) {
	uuo.defaults()
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *USERUpdateOne) SaveX(ctx context.Context) *USER {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *USERUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *USERUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uuo *USERUpdateOne) defaults() {
	if _, ok := uuo.mutation.UpdateAt(); !ok {
		v := user.UpdateDefaultUpdateAt()
		uuo.mutation.SetUpdateAt(v)
	}
}

func (uuo *USERUpdateOne) sqlSave(ctx context.Context) (_node *USER, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "USER.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := uuo.mutation.CreateAt(); ok {
		_spec.SetField(user.FieldCreateAt, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.UpdateAt(); ok {
		_spec.SetField(user.FieldUpdateAt, field.TypeTime, value)
	}
	_node = &USER{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
