// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TourProduct is the predicate function for tourproduct builders.
type TourProduct func(*sql.Selector)

// USER is the predicate function for user builders.
type USER func(*sql.Selector)
